//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animal.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalTable
    {
        public int IDAnimal { get; set; }
        public System.DateTime DataEntranceAnimal { get; set; }
        public int ViewAnimal { get; set; }
        public string NameAnimal { get; set; }
        public bool PassportAnimal { get; set; }
        public int AgeAnimal { get; set; }
        public string ServiesAnimal { get; set; }
        public System.DateTime DateEnd { get; set; }
    
        public virtual VievTable VievTable { get; set; }
    }
}
