//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Animal.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookTable
    {
        public int ArticlenumberBook { get; set; }
        public System.DateTime DateofreceiptBook { get; set; }
        public int GenreBook { get; set; }
        public string SnmauthorBook { get; set; }
        public string NameBook { get; set; }
        public System.DateTime DateofpublicationBook { get; set; }
        public bool NecessarilyBook { get; set; }
    
        public virtual GenreTable GenreTable { get; set; }
    }
}
